name: Flutter Nightly Build

on:
  # schedule:
    # schedule build every night
    # - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (1.2.3)'
        required: true
        type: string

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
      version: ${{ inputs.version }}
